### ISSUE TITLE
TimeoutError: QueuePool limit

### ISSUE THREAD

**Issue by theresthatguy** [modrzew/pokeminer#167] opened 2016-08-08 21:16 UTC
After upgrading to v0.5 with #162 
[Pastebin copy](http://pastebin.com/s57ddDU3)
`Traceback (most recent call last):
  File "worker.py", line 135, in run
    self.main()
  File "worker.py", line 214, in main
    db.add_sighting(session, raw_pokemon)
  File "/hdd/Pokemon/pokeminer-ph3/db.py", line 188, in add_sighting
    .filter(Sighting.lon == pokemon['lon']) \
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2659, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2761, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2774, in _execute_and_instances
    close_with_result=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2765, in _connection_from_session
    **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 893, in connection
    execution_options=execution_options)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 898, in _connection_for_bind
    engine, execution_options)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 334, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2039, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 376, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 1053, in _do_get
    (self.size(), self.overflow(), self._timeout))
TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30`

**Comment by Aiyubi** [comment] 2016-08-08 21:21
this is a very old issue and Im getting tons of those myself
the problem is the other exceptions that you are not showing ;)

#77 was when I tried to fix this. Will need to test tomorrow

**Comment by theresthatguy** [comment] 2016-08-08 21:24
I did not see any other errors in my log file.

**Comment by pokemonracer** [comment] 2016-08-09 01:24
Fixed this by switching from sqlite to mysql and added this to my .ini file:
innodb_buffer_pool_size=1G

**Comment by theresthatguy** [comment] 2016-08-09 02:13
What .ini file are you referring to? I am not using mysql but mariadb.

**Comment by Aiyubi** [comment] 2016-08-09 09:29
I just uploaded a PR #180 and need someone with the problem to test if this fixes it

**Comment by modrzew** [comment] 2016-08-09 21:06
#180 merged, closing.

**Closed by modrzew** 2016-08-09 21:06 UTC
