### ISSUE TITLE
Web.py Map not working

### ISSUE THREAD

**Issue by ferazambuja** [modrzew/pokeminer#18] opened 2016-07-23 19:27 UTC
I just updated to 0.2. 
No return errors everything runs.
However, there is no Pokemon or even the marker showing on the 127.0.0.1:8000. The maps shows empty.

**Comment by ferazambuja** [comment] 2016-07-23 20:58
yep I copied the old db. Should I create a new one?

**Comment by modrzew** [comment] 2016-07-23 21:00
If there are no errors then that's weird. Could you double check whether web.py doesn't raise any exceptions? There should be worker markers at least.

**Comment by ferazambuja** [comment] 2016-07-23 21:03
I did not.

**Comment by ferazambuja** [comment] 2016-07-23 21:09
Tried with a new db and folder. Same issue.
Double checked and the data on the db is new.

**Comment by modrzew** [comment] 2016-07-23 21:24
Are there any JS errors in the console, then?

**Comment by ferazambuja** [comment] 2016-07-23 21:31
Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
Uncaught TypeError: Cannot read property 'offsetWidth' of null
Failed to load resource: the server responded with a status of 404 (NOT FOUND)
GET http://127.0.0.1:8000/data 500 (INTERNAL SERVER ERROR)
GET http://127.0.0.1:8000/data 500 (INTERNAL SERVER ERROR)
GET http://127.0.0.1:8000/data 500 (INTERNAL SERVER ERROR)
GET http://127.0.0.1:8000/data 500 (INTERNAL SERVER ERROR)

https://dl.dropboxusercontent.com/u/9492397/Screen%20Shot%203.png

**Comment by modrzew** [comment] 2016-07-23 21:32
The ` GET http://127.0.0.1:8000/data 500 (INTERNAL SERVER ERROR)` is more important. Can you paste output of web.py process?

**Comment by ferazambuja** [comment] 2016-07-23 21:35
My bad there is a lot of errors coming from the web.py:
```
$ python web.py --host 127.0.0.1 -ort 8000
 * Running on http://127.0.0.1:8000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 566-785-098
127.0.0.1 - - [23/Jul/2016 17:33:57] "GET /data HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/fernandoazambuja/Downloads/pokeminer-0.2/web.py", line 65, in data
    return json.dumps(get_pokemarkers())
  File "/Users/fernandoazambuja/Downloads/pokeminer-0.2/web.py", line 107, in get_pokemarkers
    pokemons = db.get_sightings(session)
  File "/Users/fernandoazambuja/Downloads/pokeminer-0.2/db.py", line 68, in get_sightings
    trash_list = getattr(config, 'TRASH_IDS')
AttributeError: 'module' object has no attribute 'TRASH_IDS'
```

**Comment by cryzies** [comment] 2016-07-23 21:39
Did you update to the current version, he fixed the trash_id issue

**Comment by ferazambuja** [comment] 2016-07-23 21:41
Yep I'm using 0.2.
Had no issues on 0.1.

**Comment by modrzew** [comment] 2016-07-23 21:58
The fix is in master and will be released with v0.3. For a workaround, just defined an empty `TRASH_IDS` list in config:

```py
TRASH_IDS = []
```

**Comment by paperc07** [comment] 2016-07-23 22:16
I tried that and I couldnt get it working

**Comment by suppoo** [comment] 2016-07-23 22:42
I encountered this problem too, what I did:

Commented out these lines:
```
trash_list = getattr(config, 'TRASH_IDS')
if trash_list:
query = query.filter(not_(Sighting.pokemon_id.in_(config.TRASH_IDS)))
```

Also it seems map only works for Chrome and Firefox. Tried default browser on samsung S5 neo and Edge, map loads but pokemon icons are missing

**Comment by modrzew** [comment] 2016-07-24 19:52
Fix just landed in [v0.3](https://github.com/modrzew/pokeminer/releases/tag/v0.3) - could you update and tell me whether the issue is gone?

**Comment by ferazambuja** [comment] 2016-07-24 20:16
Just updated everything new. Still, doesn't work :(

**Comment by ferazambuja** [comment] 2016-07-24 21:46
v0.3.1 the map now works.

**Closed** 2016-07-25 06:59 UTC
