### ISSUE TITLE
Workers over 100% and finding no pokemon

### ISSUE THREAD

**Issue by fu20161234** [modrzew/pokeminer#40] opened 2016-07-26 12:46 UTC
So you can see here many workers are finding no pokemon. The only two that are are 6 and 7.

[2016-07-26 timestamp][  worker-2][    INFO][L 495] Point processed, 0 Pokemons seen!
[2016-07-26 timestamp][  worker-2][    INFO][L 480] Visiting point 523 (LAT, LONG)
[2016-07-26 timestamp][  worker-4][    INFO][L 495] Point processed, 0 Pokemons seen!
[2016-07-26 timestamp][  worker-4][    INFO][L 480] Visiting point 499 (LAT, LONG)
[2016-07-26 timestamp][  worker-3][    INFO][L 495] Point processed, 0 Pokemons seen!
[2016-07-26 timestamp][  worker-3][    INFO][L 480] Visiting point 527 (LAT, LONG)
[2016-07-26 timestamp][  worker-1][    INFO][L 495] Point processed, 0 Pokemons seen!
[2016-07-26 timestamp][  worker-1][    INFO][L 480] Visiting point 497 (LAT, LONG)
[2016-07-26 timestamp][  worker-6][    INFO][L 495] Point processed, 1 Pokemons seen!
[2016-07-26 timestamp][  worker-6][    INFO][L 480] Visiting point 275 (LAT, LONG)
[2016-07-26 timestamp][  worker-7][    INFO][L 495] Point processed, 0 Pokemons seen!
[2016-07-26 timestamp][  worker-7][    INFO][L 480] Visiting point 271 (LAT, LONG)
[2016-07-26 timestamp][  worker-2][    INFO][L 495] Point processed, 0 Pokemons seen!
[2016-07-26 timestamp][  worker-2][    INFO][L 480] Visiting point 524 (LAT, LONG)
[2016-07-26 timestamp][  worker-5][    INFO][L 495] Point processed, 0 Pokemons seen!
[2016-07-26 timestamp][  worker-5][    INFO][L 480] Visiting point 533 (LAT, LONG)
[2016-07-26 timestamp][  worker-8][    INFO][L 495] Point processed, 0 Pokemons seen!
[2016-07-26 timestamp][  worker-8][    INFO][L 480] Visiting point 319 (LAT, LONG)
[2016-07-26 timestamp][  worker-4][    INFO][L 495] Point processed, 0 Pokemons seen!
[2016-07-26 timestamp][  worker-4][    INFO][L 480] Visiting point 500 (LAT, LONG)
[2016-07-26 timestamp][  worker-3][    INFO][L 495] Point processed, 0 Pokemons seen!
[2016-07-26 timestamp][  worker-3][    INFO][L 480] Visiting point 528 (LAT, LONG)
[2016-07-26 timestamp][  worker-0][    INFO][L 495] Point processed, 0 Pokemons seen!
[2016-07-26 timestamp][  worker-0][    INFO][L 480] Visiting point 544 (LAT, LONG)
[2016-07-26 timestamp][  worker-1][    INFO][L 495] Point processed, 0 Pokemons seen!
[2016-07-26 timestamp][  worker-1][    INFO][L 480] Visiting point 498 (LAT, LONG)
[2016-07-26 timestamp][  worker-6][    INFO][L 495] Point processed, 1 Pokemons seen!
[2016-07-26 timestamp][  worker-6][    INFO][L 480] Visiting point 276 (LAT, LONG)

And here you can see that 6 and 7 are the only ones below 100 %. 

PokeMiner       running for 8:26:35.577778
9 workers, each visiting ~641.666666667 points per cycle (min: 625, max: 650)

[W0: C3,P0,287%]        [W1: C3,P0,282%]        [W2: C3,P0,286%]        [W3: C3,P0,287%]
[W4: C3,P0,283%]        [W5: C3,P0,288%]        [W6: C1,P157,50%]       [W7: C1,P271,49%]
[W8: C3,P0,257%]

**Comment by fu20161234** [comment] 2016-07-26 12:59
Hm, comparing worker logs now.

Worker-6 (which appeared to be working):

[2016-07-26 timestamp][  worker-6][    INFO][L 480] Visiting point 624 (LAT, LONG)
[2016-07-26 timestamp][  worker-6][    INFO][L 495] Point processed, 0 Pokemons seen!
[2016-07-26 timestamp][  worker-6][    INFO][L 600] Worker (re)starting up!
[2016-07-26 timestamp][  worker-6][    INFO][L 282] PTC login for: vjb47533
[2016-07-26 timestamp][  worker-6][    INFO][L 788] Starting new HTTPS connection (1): sso.pokemon.com
[2016-07-26 timestamp][  worker-6][    INFO][L 788] Starting new HTTPS connection (1): pgorelease.nianticlabs.com
[2016-07-26 timestamp][  worker-6][    INFO][L 404] Login successful
[2016-07-26 timestamp][  worker-6][    INFO][L 480] Visiting point 0 (LAT, LONG)
[2016-07-26 timestamp][  worker-6][    INFO][L 495] Point processed, 4 Pokemons seen!

Worker-4 (which was not and was over 100):

[2016-07-26 timestamp][  worker-4][    INFO][L 480] Visiting point 649 (LAT, LONG)
[2016-07-26 timestamp][  worker-4][    INFO][L 495] Point processed, 0 Pokemons seen!
[2016-07-26 timestamp][  worker-4][    INFO][L 480] Visiting point 0 (LAT, LONG)
[2016-07-26 timestamp][  worker-4][    INFO][L 495] Point processed, 0 Pokemons seen!

So it appears to not actually be restarting. Not getting a new connection probably means it went over the time which seems to cause issue #12 "After half an hour the DB stops updating."

So my guess is that if we get the workers restarting correctly when they reach 100% then not finding pokemon will no longer be an issue.

**Comment by fu20161234** [comment] 2016-07-26 13:24
Hey. I figured this out. Really two issues. I'll submit a PR for fixing the 100% issue. 

As for the not finding pokemon- this loop is the issue:

`while self.cycle <= 3:
            self.main(service, api_endpoint, access_token, profile_response)
            self.cycle += 1
            if self.cycle <= 3:
                self.error_code = 'SLEEP'
                time.sleep(random.randint(30, 60))
                self.error_code = None`

If getting through all three of these loops take longer than the 30 min or whatever the number is for when 0 pokemon are returned, nothing happens.

Really, we need a timer in each worker, and if that timer is over, say, 25 minutes, that worker needs to restart. But then that brings the issue of if that worker is covering too much distance, it may never finish the entire area, as it restarts halfway through. 

Thoughts?

**Comment by modrzew** [comment] 2016-07-26 13:27
I'd say more like "if worker doesn't do anything for X minutes, then poke him as something is definitely wrong". No need to restart it if it's working properly.

**Comment by fu20161234** [comment] 2016-07-26 13:29
Right, but the issue is that the worker _is_ doing stuff still. It's just returning no pokemon. Same as issue #12 . Seems that perhaps the game requires reauthentication after a longer period of time or something?

**Comment by modrzew** [comment] 2016-07-26 13:45
By "doing anything" I meant things like visiting points, seeing new Pokemon etc. - it can be monitored using `Slave.cycle` and `Slave.seen` properties. Overseer (`spawn_workers`) shouldn't care that worker does *something* - if it doesn't observe new spawns, it's not doing its job, therefore it might have to be restarted.

**Comment by fu20161234** [comment] 2016-07-26 13:56
Unless I'm still not understanding you, it is doing stuff. It is visiting new points still, it just sees that those points have 0 pokemon at them. I personally like the suggestion in the other issue. Once X amount of time has elapsed, simply request a new token, but don't restart completely, in order to prevent losing the place in the square.

**Comment by fu20161234** [comment] 2016-07-26 14:00
Submitted PR #41 to fix the going above 100% issue. That's just a display issue.

**Comment by fu20161234** [comment] 2016-07-26 14:01
So even though it's still logging that it's visiting points and whatnot, you don't think it actually is even trying to get that data?

**Comment by modrzew** [comment] 2016-07-26 14:08
I realized that I'm talking about different issue, where worker just stops doing anything after some time passes. It seems like visiting points and seeing 0 Pokemon each time (which you talked about) is a different issue.

Nonetheless, from the overseer's point of view, worker can spend its time on anything: visiting stops on map, DDoSing servers of some other games, solving the world's hunger problem etc., it doesn't care - as long as it adds new Pokemon to the database. If it doesn't (even though it's working really hard!), then something's wrong and it may be wise to replace it with new worker.

I'd add that as a failsafe for *unexpected* issues with workers, so that they can continue gathering data (although slower). And after issues are identified (like with the expiring token), they should be taken care of individually.

By the way, thanks for the pull request :smiley:

**Comment by fu20161234** [comment] 2016-07-26 14:19
> I realized that I'm talking about different issue, where worker just stops doing anything after some time passes. It seems like visiting points and seeing 0 Pokemon each time (which you talked about) is a different issue.

Hm, now that you mention it, I did submit one other issue yesterday for the same thing. So I've seen both cases.

Everything you said makes sense though, yeah.

And sure, glad to help!

**Comment by elx0r** [comment] 2016-07-28 09:34
Any solution for this yet?

**Comment by fu20161234** [comment] 2016-07-28 15:11
Which part? The over 100% bug is fixed, but that doesn't actually break anything so it's safe to ignore. As for the finding no pokemon part, for some reason the workers seem to go bad after a while. My solution was to change it from running 3 cycles before restarting to just running one cycle, and I made sure all my workers were completing their cycle in under 15 minutes by using the timer.

**Comment by modrzew** [comment] 2016-07-29 22:50
A few things just landed in master:

- ability to modify how many cycles worker should run before restarting (in config)
- overseer (`spawn_workers` main loop) visits each worker every 5 minutes and if it doesn't increase its seen counter, kills it and spawns new worker
- switched to the most recent version of pgoapi, which has somewhat better error handling

Please check whether that improved things for you. I'm closing this issue, but feel free to open new one if the problem isn't gone.

**Closed by modrzew** 2016-07-29 22:50 UTC
Labels: investigate
