### ISSUE TITLE
Exception (126 Error)

### ISSUE THREAD

**Issue by TokarevG** [modrzew/pokeminer#218] opened 2016-08-12 17:49 UTC
I keep getting this exception

> [2016-08-12 20:44:11,831][    INFO][requests.packages.urllib3.connectionpool] Starting new HTTPS connection (1): sso.pokemon.com
[2016-08-12 20:44:12,915][    INFO][pgoapi.auth] PTC User Login successful.
[2016-08-12 20:44:12,915][    INFO][pgoapi.auth] Request PTC Access Token...
[2016-08-12 20:44:13,174][    INFO][pgoapi.auth] PTC Access Token successfully retrieved.
[2016-08-12 20:44:13,174][    INFO][worker-0] Starting RPC login sequence (app simulation)
[2016-08-12 20:44:13,174][    INFO][pgoapi.pgoapi] Creating a new request...
[2016-08-12 20:44:13,174][    INFO][pgoapi.pgoapi] Adding 'GET_PLAYER' to RPC request
[2016-08-12 20:44:13,174][    INFO][pgoapi.pgoapi] Adding 'GET_HATCHED_EGGS' to RPC request
[2016-08-12 20:44:13,174][    INFO][pgoapi.pgoapi] Adding 'GET_INVENTORY' to RPC request
[2016-08-12 20:44:13,174][    INFO][pgoapi.pgoapi] Adding 'CHECK_AWARDED_BADGES' to RPC request
[2016-08-12 20:44:13,174][    INFO][pgoapi.pgoapi] Adding 'DOWNLOAD_SETTINGS' to RPC request including arguments
[2016-08-12 20:44:13,174][   ERROR][worker-0] A wild exception appeared!
Traceback (most recent call last):
  File "C:\test\pokeminer\worker.py", line 146, in login
    provider=config.ACCOUNTS[self.worker_no][2],
  File "D:\Python\Python35-32\lib\asyncio\futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "D:\Python\Python35-32\lib\asyncio\tasks.py", line 296, in _wakeup
    future.result()
  File "D:\Python\Python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "D:\Python\Python35-32\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\test\pokeminer\worker.py", line 126, in inner
    result = method(*args, **kwargs)
  File "c:\test\pokeminer\src\pgoapi\pgoapi\pgoapi.py", line 175, in login
    response = self.app_simulation_login()
  File "c:\test\pokeminer\src\pgoapi\pgoapi\pgoapi.py", line 152, in app_simulation_login
    response = request.call()
  File "c:\test\pokeminer\src\pgoapi\pgoapi\pgoapi.py", line 222, in call
    request.activate_signature(lib_path)
  File "c:\test\pokeminer\src\pgoapi\pgoapi\rpc_api.py", line 81, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "D:\Python\Python35-32\lib\ctypes\__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "D:\Python\Python35-32\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
[2016-08-12 20:44:13,174][    INFO][worker-0] Restarting

**Comment by YonderGod** [comment] 2016-08-12 18:27
duplicate of #208, #215

**Closed** 2016-08-12 19:40 UTC
