### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by theresthatguy** [modrzew/pokeminer#174] opened 2016-08-09 02:39 UTC
`./web.sh
 * Running on http://127.0.0.1:8000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 208-815-793
/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/default_comparator.py:153: SAWarning: The IN-predicate on "sightings.pokemon_id" was invoked with an empty sequence. This results in a contradiction, which nonetheless can be expensive to evaluate.  Consider alternative strategies for improved performance.
  'strategies for improved performance.' % expr)
127.0.0.1 - - [08/Aug/2016 21:32:10] "GET /report HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/hdd/Pokemon/pokeminer-ph3/web.py", line 198, in report_main
    google_maps_key=config.GOOGLE_MAPS_KEY,
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/hdd/Pokemon/pokeminer-ph3/templates/report.html", line 128, in top-level template code
    <a href="/report/{{ icon[0] }}"><img src="../static/larger-icons/{{ icon[0] }}.png" title="#{{ icon[0] }} {{ icon[1] }}"></a>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 7: ordinal not in range(128)`

**Comment by nhumber** [comment] 2016-08-09 02:56
same issue here, all is running good just web.py isnt working, i had it working on my windows PC but when i migrated over to a linux box i get this error also.

**Comment by grenadesonfire** [comment] 2016-08-09 03:17
I found the error to be in this line:
<a href="/report/{{ icon[0] }}"><img src="../static/larger-icons/{{ icon[0] }}.png" title="#{{ icon[0] }} {{ icon[1] }}"></a>

This controls the icons appearing for the top 30 line in the report. Not sure why this is happening other than there might be a utf-8 character in here and python threw a fit.

**Comment by nhumber** [comment] 2016-08-09 03:37
thanks, 
grenadesonfire temp fix works perfectly.

**Comment by Aiyubi** [comment] 2016-08-09 06:36
duplicate of #161

**Comment by modrzew** [comment] 2016-08-09 13:44
It should be fixed as of c3fd59dc64f94 (in master).

**Closed by modrzew** 2016-08-09 13:44 UTC
